In [26]:
import numpy as np
import pandas as pd
%matplotlib inline
import matplotlib.pyplot as plt

In [27]:
df = pd.read_excel('placement_dataset.xlsx')

In [28]:
df.head()

city      cgpa     iq  placement
0     New York  6.800000  123.0          1
1  Los Angeles  5.900000  106.0          0
2      Chicago  5.975303  121.0          0
3     New York  7.400000  132.0          1
4  Los Angeles  5.800000  142.0          0

In [29]:
X = df.iloc[:,1:4]

In [30]:
X.head()

cgpa     iq  placement
0  6.800000  123.0          1
1  5.900000  106.0          0
2  5.975303  121.0          0
3  7.400000  132.0          1
4  5.800000  142.0          0

In [31]:
Y = df.iloc[:,-1:]

In [32]:
Y.head()

placement
0          1
1          0
2          0
3          1
4          0

In [33]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.1,random_state = 0)

In [34]:
X_train.head()

cgpa          iq  placement
1006  5.227825   74.374939          0
690   6.167620  152.691417          1
1049  7.860808  225.575927          1
984   7.822171  181.453788          1
957   5.207986  229.036783          0

In [35]:
Y_train.head()

placement
1006          0
690           1
1049          1
984           1
957           0

In [36]:
Y_test.head()

placement
395           1
860           0
477           1
671           1
1002          1

In [37]:
from sklearn.preprocessing import StandardScaler

In [38]:
scaler = StandardScaler()

In [39]:
X_train= scaler.fit_transform(X_train)

In [40]:
X_train

array([[-0.67119283, -0.92148181, -1.07557554],
       [ 0.15018071,  0.75911037,  0.92973479],
       [ 1.63001413,  2.32313801,  0.92973479],
       ...,
       [ 0.39695163,  0.02329011, -1.07557554],
       [-0.00677746, -0.02353974,  0.92973479],
       [-1.91331939, -0.93648332, -1.07557554]])

In [41]:
X_test= scaler.fit_transform(X_test)

In [42]:
X_test

array([[ 0.27108776,  0.78237638,  1.03704952],
       [-2.16743291, -1.5480041 , -0.96427411],
       [-0.18980406, -0.55531206,  1.03704952],
       [-0.23186795, -1.21115067,  1.03704952],
       [-1.04969124, -1.11746044,  1.03704952],
       [-1.03113621,  0.66571845,  1.03704952],
       [ 1.32959991,  0.56157207, -0.96427411],
       [-0.51033921, -0.0910118 , -0.96427411],
       [ 1.1459633 , -2.21235278, -0.96427411],
       [ 1.68277348, -0.03387295,  1.03704952],
       [-0.49676061,  1.26051195,  1.03704952],
       [ 0.90123526, -0.27239772,  1.03704952],
       [-0.47894943,  0.26386425, -0.96427411],
       [ 0.23753728, -0.95448255, -0.96427411],
       [ 0.1441039 , -0.47061265,  1.03704952],
       [-0.22593611,  0.3034145 , -0.96427411],
       [-0.77034922,  0.15145205,  1.03704952],
       [-0.92672924,  0.6368349 ,  1.03704952],
       [-0.3743477 ,  0.95755202,  1.03704952],
       [-0.46751059, -2.69991473, -0.96427411],
       [ 0.16231596, -0.11447542, -0.964

In [43]:
from sklearn.linear_model import LogisticRegression

In [44]:
clf = LogisticRegression()

In [45]:
clf.fit(X_train,Y_train.values.ravel())

LogisticRegression()

In [46]:
Y_pred = clf.predict(X_test)

In [47]:
Y_pred

array([1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1,
       1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0,
       1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1,
       1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1])

In [48]:
Y_test

placement
395           1
860           0
477           1
671           1
1002          1
...         ...
897           1
769           0
893           1
487           0
965           1

[110 rows x 1 columns]

In [49]:
from sklearn.metrics import accuracy_score

In [50]:
accuracy_score(Y_test,Y_pred)

1.0